version: "3"

networks:
  public-net:
    ipam:
      driver: default
      config:
        - subnet: 10.30.0.0/24
          gateway: 10.30.0.100
  site-1:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
  site-2:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24

services:
  # Bootstrap/TURN Node

  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.30.0.1
    hostname: bootstrap-node
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --global.primary-endpoint=10.30.0.1
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.ipv4-network=10.100.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.in-memory
      - --services.api.mesh
      - --services.api.admin
      - --services.dashboard.enabled
      - --services.dashboard.listen-address=:8080
      # Enable the WebRTC API to help nodes with ICE connectivity.
      - --services.api.webrtc
      - --services.api.stun-servers=stun:10.30.0.1:3478
      # Enable an embedded TURN server. You can optionally use a public one.
      - --services.turn.enabled
      - --services.turn.public-ip=10.30.0.1
    ports:
      - 8443:8443
      - 8080:8080
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-1-peer:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
      site-1:
    hostname: site-1-peer
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=10.30.0.1:8443
      - --mesh.direct-peers=site-2-peer
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-2-peer:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
      site-2:
    hostname: site-2-peer
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=10.30.0.1:8443
      - --mesh.direct-peers=site-1-peer
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
